# Generated by Django 4.2.6 on 2024-01-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topfragmarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('cavite', 'Cavite'), ('laspiñas', 'Las Piñas'), ('makati', 'Makati'), ('Pasig', 'Pasig')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('discussion', 'Discussion'), ('Advice', 'Advice'), ('gaming', 'Gaming'), ('tech', 'Tech')], max_length=50),
        ),
    ]
